table Financial_Data
	lineageTag: f4ad8070-5abb-42ff-9c92-90ac0dbbfcb7

	column 'Financial Statement Breakdown'
		dataType: string
		lineageTag: 6334c16f-f375-453d-ac65-d15802c1cf35
		summarizeBy: none
		sourceColumn: Financial Statement Breakdown

		annotation SummarizationSetBy = Automatic

	column Entity
		dataType: string
		lineageTag: 76706947-7681-43f5-8762-ff5066592b36
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column Actual/Budget
		dataType: string
		lineageTag: 0e8206df-dee2-4161-af81-2138c2b46170
		summarizeBy: none
		sourceColumn: Actual/Budget

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54335557-0a8b-4cd8-8300-12a18838df29
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: double
		lineageTag: 258df10c-eae0-4a47-a259-65d6154de643
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Financial_Data = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\VijayPerepa\Desktop\Financial Reporting Example Dummy Data (1) (1).xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Financial_Data", Kind = "Table"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Financial Statement Breakdown", type text}, {"Entity", type text}, {"Actual/Budget", type text}, {"4/1/2015", type number}, {"5/1/2015", type number}, {"6/1/2015", type number}, {"7/1/2015", type number}, {"8/1/2015", type number}, {"9/1/2015", type number}, {"10/1/2015", type number}, {"11/1/2015", type number}, {"12/1/2015", type number}, {"1/1/2016", type number}, {"2/1/2016", type number}, {"3/1/2016", type number}, {"4/1/2016", type number}, {"5/1/2016", type number}, {"6/1/2016", type number}, {"7/1/2016", type number}, {"8/1/2016", type number}, {"9/1/2016", type number}, {"10/1/2016", type number}, {"11/1/2016", type number}, {"12/1/2016", type number}, {"1/1/2017", type number}, {"2/1/2017", type number}, {"3/1/2017", type number}, {"4/1/2017", type number}, {"5/1/2017", type number}, {"6/1/2017", type number}, {"7/1/2017", type number}, {"8/1/2017", type number}, {"9/1/2017", type number}, {"10/1/2017", type number}, {"11/1/2017", type number}, {"12/1/2017", type number}, {"1/1/2018", type number}, {"2/1/2018", type number}, {"3/1/2018", type number}}, "en-US"),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed column type", {"Financial Statement Breakdown", "Entity", "Actual/Budget"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "Date"}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Renamed Columns", {{"Date", type date}}, "en-US")
				in
				  #"Changed Type with Locale"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

