table Financial_Categories
	lineageTag: 2a0c157a-2b9d-47a5-b09d-224d7c4fe367

	column 'Financial Statement List'
		dataType: string
		lineageTag: 646b98c2-f82b-4899-8537-b4040c45bd97
		summarizeBy: none
		sourceColumn: Financial Statement List

		annotation SummarizationSetBy = Automatic

	column 'Sub Category'
		dataType: string
		lineageTag: c6463694-c31a-4af7-854c-ee665c925fee
		summarizeBy: none
		sourceColumn: Sub Category

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c6542f1d-d1b1-43d6-b430-13c038aa0483
		summarizeBy: none
		sourceColumn: Category
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: c09ee750-0428-4d75-90fc-6c6466d53a66
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	hierarchy 'Category Hierarchy'
		lineageTag: bf4cf975-56b5-45c8-bcaa-a135688e2db5

		level Category
			lineageTag: b7851d85-afc6-4a20-aec5-7e0c11a60d27
			column: Category

		level 'Sub Category'
			lineageTag: ee88f438-82c3-4d17-b078-adab41305605
			column: 'Sub Category'

		level 'Financial Statement List'
			lineageTag: e2d1c760-a177-422b-9414-1b6cef6aaee9
			column: 'Financial Statement List'

	partition Financial_Categories = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\VijayPerepa\Desktop\Financial Reporting Example Dummy Data (1) (1).xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Financial_Categories", Kind = "Table"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Financial Statement List", type text}, {"Sub Category", type text}, {"Category", type text}}, "en-US"),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed column type", "Index", each if [Category] = "Revenue" then 1 else 2),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Index", Int64.Type}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

